language: node_js

sudo: true

dist: trusty

node_js:
  - "5.0"

before_install:
- ./.travis.before

install: npm update

cache:
  apt: true
  directories:
    - node_modules

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
