language: node_js

sudo: true

dist: trusty

node_js:
  - "5.0"

env:
- ZMQ="git://github.com/zeromq/zeromq4-1.git -b v4.1.2" SODIUM="git://github.com/jedisct1/libsodium.git -b 1.0.3"

before_install:
- sudo apt-get install uuid-dev
- '[ -z "$SODIUM" ] || git clone --depth 1 $SODIUM libsodium'
- '[ -z "$SODIUM" ] || cd libsodium'
- '[ -z "$SODIUM" ] || ./autogen.sh'
- '[ -z "$SODIUM" ] || ./configure'
- '[ -z "$SODIUM" ] || make'
- '[ -z "$SODIUM" ] || sudo make install'
- '[ -z "$SODIUM" ] || cd ..'
- git clone --depth 1 $ZMQ zmqlib
- cd zmqlib
- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo /sbin/ldconfig
- cd ..

cache:
  apt: true
  directories:
    - node_modules

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
