language: node_js

sudo: true

dist: trusty

node_js:
  - "5.0"

env:
- ZMQ="git://github.com/zeromq/zeromq4-1.git -b v4.1.2" SODIUM="git://github.com/jedisct1/libsodium.git -b 1.0.3"

before_install:
- 'export SKIP=`[ -d "zmqlib" ] ||`'
- '$SKIP || sudo apt-get -y install uuid-dev'
- '$SKIP || [ -z "$SODIUM" ] || git clone --depth 1 $SODIUM libsodium'
- '$SKIP || [ -z "$SODIUM" ] || cd libsodium'
- '$SKIP || [ -z "$SODIUM" ] || ./autogen.sh'
- '$SKIP || [ -z "$SODIUM" ] || ./configure'
- '$SKIP || [ -z "$SODIUM" ] || make'
- '$SKIP ||[ -z "$SODIUM" ] || sudo make install'
- '$SKIP ||[ -z "$SODIUM" ] || cd ..'
- '$SKIP || git clone --depth 1 $ZMQ zmqlib'
- '$SKIP || cd zmqlib'
- '$SKIP || ./autogen.sh'
- '$SKIP || ./configure'
- '$SKIP || make'
- '$SKIP || sudo make install'
- '$SKIP || sudo /sbin/ldconfig'
- '$SKIP || cd ..'

cache:
  apt: true
  directories:
    - node_modules
    - zmqlib

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
